### ISSUE TITLE
WebSphere WebJars

### ISSUE THREAD

**Issue by dweidele** [l0rdn1kk0n/wicket-webjars#53]
Hi,

I have read several issues around WebJars on WebSphere. I am running into some issue where for bootstrap-datetimepicker the CSS/JS references cannot be determined. Especially I notice where there should be a version string in the URL, there is just null.

I have read there have been some fixes going on, but now I am not exactly sure how to use / configure for WebSphere.

I'd be glad if you could advise.

Wicket 8.0.0-M5
WebJars 2.0.1
Bootstrap-Extensions 2.0.0-M2

Thanks,
Daniel

**Comment by martin-g** [comment]
Hi,

You need to use the latest version of wicket-webjars depending on the version of Wicket you use. Please consult with the README in the root of the project for that.

WebSphere is a commercial product and I don't have access to it to test but recently another user debugged it and contributed https://github.com/l0rdn1kk0n/wicket-webjars/commit/1cc470429f2a675d3d8447df4e278e86e60f65df
So, you just need to use WebSphereWebjarsSettings instead of WebjarsSettings in YourApplication#init().

**Comment by dweidele** [comment]
Oh, I did not notice WebSphereWebjarsSettings, thanks! Works for me 👍 

Just in case, if you'd ever need to test on WebSphere you can use the Java Liberty Profile on IBM Bluemix (30-days free trial).

**Comment by martin-g** [comment]
I'm glad it worked!

Well, it seems there are many flavors of WebSphere - https://github.com/l0rdn1kk0n/wicket-webjars/issues/43#issuecomment-229651572 :-)
Honestly, I am not really keen on dealing with it. I've heard many bad things about it :-/
